---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generate-config-pipeline
  namespace: pkumari-tenant
  labels:
    appstudio.openshift.io/component: rhtap-e2e-test
    appstudio.openshift.io/application: rhtap-nested-ci
spec:
  tasks:
    - name: echo-generated-filename
      taskSpec:
        steps:
          - name: echo-config-files
            image: quay.io/openshift-pipeline/ci
            script: |
              #!/usr/bin/env bash

              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
              source ~/.bashrc
              nvm install node
              npm install --global yarn
              node -v
              yarn -v

              cd "$(mktemp -d)"
              echo -e "[INFO]Cloning repo name 'rhtap-e2e' with revision 'handlemultipleconfigautomatically' from url 'https://github.com/prietyc123/rhtap-e2e.git'"
              git clone "https://github.com/prietyc123/rhtap-e2e.git" .
              git checkout handlemultipleconfigautomatically

              # generate config files in generated-config directory
              yarn
              yarn generate-config

              configDir="$(pwd)/generated-config"
              # Initialize an empty file array
              files=()

              for file in "$configDir"/*; do
                files+=("$(basename "$file")")
              done
              
              # Start the created pipeline with multiple configfile
              for filename in "${files[@]}"
              do
                configFile="$configDir/$filename"

                # read the file and extract the 'ocp' version value
                ocp_version=$(node -e "
                  const config = require('$configFile');
                  console.log(config.globals.suites.softwareTemplates.pipeline.ocp);
                ")
                tkn pipeline start -f https://raw.githubusercontent.com/prietyc123/rhtap-e2e/handlemultipleconfigautomatically/integration-tests/pipelines/echo-test-pipeline.yaml --param TEST="$ocp_version"
              done
